#######################
# Theme Customization #
#######################

title: DRL_in_CV_Papers          # appears in the header and the HTML <title> tag
author: Aditya Ganeshan     # appears in an HTML <meta> tag, as well as feed.xml
description: >           # appears in an HTML <meta> tag, as well as feed.xml
  A Quick Jekyll Website for the published research in Computer Vision which use Reinforcement learning. 
slogan: Showtime!        # appears in the header, alongside the title
avatar: /i/avatar_3.png    # appears as portrait in the header
banner: /DRL_in_CV_Papers/i/mountains.svg # appears as background in the header
url: http://jekyllrb.com # used by plugins to generate feed.xml and sitemap.xml
baseurl: '/DRL_in_CV_Papers/'              # prepended to all absolute filepaths
repo: https://github.com//rlue.github.io # appears in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Papers
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Course
    url: https://bardofcodes.github.io/DRL_in_CV/
    outbound: true      # this key sets a link to open in a new window.
    icon: /i/icons.svg#portfolio
  - name: GitHub
    url: https://github.com/BardOfCodes/DRL_in_CV_Papers
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: adityaganeshan       # you know, to protect you from bots. (handle and domain
    domain: gmail.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: cat_listing  }
  - scope:  { type:   category }
    values: { layout: cat_listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
